language: cpp

compiler:
  - gcc
  - clang
    
install:
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get purge cmake -qq
  - sudo apt-get install cmake -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - git clone https://github.com/glfw/glfw
  - mkdir glfw/build
  - cd glfw/build
  - cmake .. -DBUILD_SHARED_LIBS=ON
  - make VERBOSE=1
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  
script:
  - cmake ..
  - make VERBOSE=1
  - sudo make install

os:
  - linux